import axios from "axios";
import { Request, Response } from "express";
import asyncHandler from "express-async-handler";
import { Employee } from "../models/Employee";
import {
  createEmployeeSchema,
  updateEmployeeSchema,
} from "../validators/employeeValidator";
import { generatePassword } from "../utils/autoGenratePassword";
import { sendMail } from "../mailer/mailer";
import { newEmployeeTemplate } from "../mailer/template";
import dotenv from "dotenv";

dotenv.config();

export const createEmployee = asyncHandler(async (req: any, res: Response) => {
  const validatedData = createEmployeeSchema.parse(req.body);
  if (!req.user) {
    res.status(403);
    throw new Error("Unauthorized access: Missing user information");
  }
  const { companyId, companyName } = req.user;
  const employeeData = {
    ...validatedData,
    companyId: companyId,
  };
  const employee = await Employee.create(employeeData);
  const autoGeneratedPassword = generatePassword();
  console.log(employee);
  console.log(autoGeneratedPassword);
  try {
    // Send a request to create the user account
    const userPayload = {
      email: employee.email,
      password: autoGeneratedPassword, // You can use a default or generated password
      companyId: employee.companyId,
      role: "employee", // Adjust the role as per your requirements
      mobile: employee.phone,
      fullName: "Default Name",
      companyName: companyName,
      employeeId: employee._id,
    };
    await axios.post(`${process.env.AUTH_BASE_URL}/signup`, userPayload);

    // Notify the employee via email
    await sendMail(
      employee.email,
      "Welcome to Our Company",
      newEmployeeTemplate(employee, autoGeneratedPassword)
    );

    res.status(201).json(employee);
  } catch (error) {
    console.error("Failed to create user:");
    await Employee.findByIdAndDelete(employee.id);
    res.status(500);
    throw new Error(
      "Failed to create user account. Employee creation rolled back."
    );
  }
});

export const getEmployees = asyncHandler(
  async (req: Request, res: Response) => {
    const userId = req.user.companyId;
    if (!userId) {
      res.status(403);
      throw new Error("Unauthorized access: Missing user information");
    }
    const filter: any = { companyId: userId };
    const employees = await Employee.find(filter)
      .populate("roleId")
      .populate("managerId");
    res.json(employees);
  }
);

export const updateEmployeeStatus = asyncHandler(
  async (req: Request, res: Response) => {
    const { id } = req.params;
    const { status } = req.body;

    const employee = await Employee.findByIdAndUpdate(
      id,
      { status },
      { new: true }
    );

    if (!employee) {
      res.status(404);
      throw new Error("Employee not found");
    }

    res.json(employee);
  }
);

export const updateEmployee = asyncHandler(
  async (req: Request, res: Response) => {
    const { id } = req.params;
    const updateData = updateEmployeeSchema.parse(req.body);

    const employee = await Employee.findByIdAndUpdate(id, updateData, {
      new: true,
      runValidators: true,
    });

    if (!employee) {
      res.status(404);
      throw new Error("Employee not found");
    }

    res.json(employee);
  }
);
export const deleteEmployee = asyncHandler(
  async (req: Request, res: Response) => {
    const { id } = req.params;

    const employee = await Employee.findByIdAndDelete(id);

    if (!employee) {
      res.status(404);
      throw new Error("Employee not found");
    }

    res.json({ message: "Employee deleted successfully" });
  }
);
